version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:0.24.1
    environment:
      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "9600:9600"
    networks:
      - zeebe_network

  zeebe-http-worker:
    container_name: zeebe-http-worker
    image: camunda/zeebe-http-worker:latest
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
    depends_on:
      - zeebe
    networks:
      - zeebe_network
